/*!CK:2395336663!*//*1455220471,*/

if (self.CavalryLogger) { CavalryLogger.start_js(["LfPtx"]); }

__d('AdsProgressBar.react',['joinClasses','React','cx'],function a(b,c,d,e,f,g,h,i,j){if(c.__markCompiled)c.__markCompiled();var k=i.PropTypes,l={xsmall:"_2n01",small:"_5nak",medium:"_5nal",large:"_5nam"},m=i.createClass({displayName:'AdsProgressBar',propTypes:{animated:k.bool,label:k.string,min:k.number,max:k.number,size:k.oneOf(['xsmall','small','medium','large']),value:k.number,error:k.number,striped:k.bool},getDefaultProps:function(){return {animated:false,label:null,min:0,max:100,value:0,size:'large',error:null,striped:false};},render:function(){var n=this.props.min,o=this.props.max,p=Math.max(n,Math.min(o,this.props.value)),q=(p-n)/(o-n)*100+'%',r="_5nat"+(p===o?' '+"_5nan":'')+(p===n?' '+"_5nao":''),s=h("_5nap"+(!!this.props.animated?' '+"_5naq":''),l[this.props.size]),t=this.props.label,u=null;if(t)u=i.createElement('span',{className:"_5nar"},t);var v=null;if(t)v=i.createElement('span',{className:"_5nar _5nas"},t);var w=this.props.error,x=null;if(w){var y=(w-n)/(p-n)*100+'%';x=i.createElement('div',{className:"_5nat _5nc9",style:{width:y}});}var z=null;if(this.props.striped)z=i.createElement('div',{className:"_5nat _4g9k"});return (i.createElement('div',babelHelpers._extends({},this.props,{className:h(this.props.className,s)}),v,i.createElement('div',{className:r,style:{width:q}},x,u,z)));}});f.exports=m;},null);
__d('AdsXUIProgressBar.react',['AdsProgressBar.react','React','cx','joinClasses'],function a(b,c,d,e,f,g,h,i,j,k){if(c.__markCompiled)c.__markCompiled();var l=i.PropTypes,m=i.createClass({displayName:'AdsXUIProgressBar',propTypes:{value:l.number},render:function(){return (i.createElement(h,babelHelpers._extends({},this.props,{animated:true,className:k(this.props.className,"_qss"),size:'small',value:this.props.value})));}});f.exports=m;},null);
__d('BUIProgressBar.react',['Image.react','React','cx','joinClasses'],function a(b,c,d,e,f,g,h,i,j,k){'use strict';if(c.__markCompiled)c.__markCompiled();var l=i.PropTypes,m=248,n=i.createClass({displayName:'BUIProgressBar',propTypes:{icon:l.object,isBuffering:l.bool,isError:l.bool,isSuccess:l.bool,message:l.string,percentage:l.number,width:l.number},getDefaultProps:function(){return {isBuffering:false,isSuccess:false,isError:false,width:m};},_renderLabel:function(){if(!this.props.icon&&!this.props.message)return null;var o;if(this.props.icon)o=i.createElement(h,{className:"__q1",src:this.props.icon});return (i.createElement('div',{className:"__q2"},o,this.props.message));},_renderProgress:function(){if(this.props.isBuffering)return (i.createElement('div',{className:"__q3",style:{width:'100%'}}));var o=+this.props.width,p=Math.round(+this.props.percentage/100*o);if(p>o)p=o;return (i.createElement('div',{className:"__q6"},i.createElement('div',{className:"__q7",style:{width:p+'px'}})));},_getWidth:function(){var o=+this.props.width;return {width:(o>m?m:o)+'px'};},render:function(){var o=k("__qa"+(this.props.isComplete===true?' '+"__qb":'')+(this.props.isError===true?' '+"__qc":''),this.props.className);return (i.createElement('div',{className:o,style:this._getWidth()},this._renderProgress(),this._renderLabel()));}});f.exports=n;},null);
__d('FansJewel',['AsyncRequest'],function a(b,c,d,e,f,g,h){if(c.__markCompiled)c.__markCompiled();function i(j){'use strict';j.subscribe('marked-seen',function(){new h('/ajax/pages/fans_seen.php').setMethod('POST').send();});}f.exports=i;},null);
__d("XPagesPresenceController",["XController"],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports=c("XController").create("\/pages\/presence\/",{});},null);
__d('PagePresencePoller',['ActorURI','AsyncRequest','UserActivity','XPagesPresenceController'],function a(b,c,d,e,f,g,h,i,j,k){'use strict';if(c.__markCompiled)c.__markCompiled();var l=90000,m=0,n=function(p){m=Date.now();var q=h.create(k.getURIBuilder().getURI(),p);new i().setURI(q).send();},o={init:function(p){j.subscribe(function(){if(Date.now()-m>l)n(p);});setInterval(function(){if(j.isActive())n(p);},l);}};f.exports=o;},null);
__d("XBulkVideoUploadController",["XController"],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports=c("XController").create("\/video\/bulk_upload\/",{target_id:{type:"String",required:true}});},null);
__d("XPagesManagerNotificationsController",["XController"],function a(b,c,d,e,f,g){c.__markCompiled&&c.__markCompiled();f.exports=c("XController").create("\/{page_token}\/notifications\/",{cursor:{type:"String"},field_type:{type:"Int"},section:{type:"Enum",enumType:1},subsection:{type:"String"},entry_point:{type:"Enum",enumType:1},proposal_ids:{type:"IntVector"},default_cta:{type:"String"},local_landing:{type:"Int"},website_landing:{type:"Int"},campaign_id:{type:"Int"},ref:{type:"String"},target_story:{type:"String"},content_id:{type:"Int"},page_token:{type:"String",required:true},business_id:{type:"Int"}});},null);